// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SetUpEstateAgentDBWeb.Models;

#nullable disable

namespace SetUpEstateAgentDBWeb.Migrations
{
    [DbContext(typeof(EstateAgentContext))]
    [Migration("20240620144158_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SetUpEstateAgentDBWeb.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BOOKING_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BuyerId")
                        .HasColumnType("int")
                        .HasColumnName("BUYER_ID");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int")
                        .HasColumnName("PROPERTY_ID");

                    b.Property<DateTime?>("Time")
                        .HasColumnType("datetime2")
                        .HasColumnName("TIME");

                    b.HasKey("Id");

                    b.ToTable("booking");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BuyerId = 2,
                            PropertyId = 2,
                            Time = new DateTime(2024, 6, 27, 15, 41, 56, 646, DateTimeKind.Local).AddTicks(4916)
                        },
                        new
                        {
                            Id = 2,
                            BuyerId = 3,
                            PropertyId = 3,
                            Time = new DateTime(2024, 7, 4, 15, 41, 56, 646, DateTimeKind.Local).AddTicks(4966)
                        },
                        new
                        {
                            Id = 3,
                            BuyerId = 1,
                            PropertyId = 4,
                            Time = new DateTime(2024, 6, 28, 15, 41, 56, 646, DateTimeKind.Local).AddTicks(4969)
                        });
                });

            modelBuilder.Entity("SetUpEstateAgentDBWeb.Models.Buyer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BUYER_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ADDRESS");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FIRST_NAME");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PHONE");

                    b.Property<string>("Postcode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("POSTCODE");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SURNAME");

                    b.HasKey("Id");

                    b.ToTable("buyer");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "1 the High Street",
                            FirstName = "Patel",
                            Phone = "08700456789",
                            Postcode = "AV1 1VA",
                            Surname = "Sadia"
                        },
                        new
                        {
                            Id = 2,
                            Address = "2 the Low Street",
                            FirstName = "Kamran",
                            Phone = "08700123654",
                            Postcode = "AV2 2VA",
                            Surname = "Liaqat"
                        },
                        new
                        {
                            Id = 3,
                            Address = "5 the Round Street",
                            FirstName = "Saeed",
                            Phone = "08700555555",
                            Postcode = "AV5 5VA",
                            Surname = "Mirza"
                        });
                });

            modelBuilder.Entity("SetUpEstateAgentDBWeb.Models.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PROPERTY_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ADDRESS");

                    b.Property<int>("Bathrooms")
                        .HasColumnType("int")
                        .HasColumnName("NUMBER_OF_BATHROOMS");

                    b.Property<int>("Bedrooms")
                        .HasColumnType("int")
                        .HasColumnName("NUMBER_OF_BEDROOMS");

                    b.Property<int?>("BuyerId")
                        .HasColumnType("int")
                        .HasColumnName("BUYER_ID");

                    b.Property<bool>("Garden")
                        .HasColumnType("bit")
                        .HasColumnName("GARDEN");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("POSTCODE");

                    b.Property<decimal?>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PRICE");

                    b.Property<int>("SellerId")
                        .HasColumnType("int")
                        .HasColumnName("SELLER_ID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)")
                        .HasColumnName("STATUS");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)")
                        .HasColumnName("TYPE");

                    b.HasKey("Id");

                    b.ToTable("property");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "3 the Avenue",
                            Bathrooms = 0,
                            Bedrooms = 4,
                            Garden = true,
                            Postcode = "TA1 1AT",
                            Price = 450000m,
                            SellerId = 1,
                            Status = "FORSALE",
                            Type = "HOUSE"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Flat 4, the Avenue",
                            Bathrooms = 0,
                            Bedrooms = 2,
                            Garden = false,
                            Postcode = "TA2 2AT",
                            Price = 300000m,
                            SellerId = 2,
                            Status = "FORSALE",
                            Type = "FLAT"
                        },
                        new
                        {
                            Id = 3,
                            Address = "5 the Road",
                            Bathrooms = 0,
                            Bedrooms = 3,
                            Garden = true,
                            Postcode = "TA2 2AT",
                            Price = 350000m,
                            SellerId = 3,
                            Status = "FORSALE",
                            Type = "BUNGALOW"
                        },
                        new
                        {
                            Id = 4,
                            Address = "7 the Road",
                            Bathrooms = 0,
                            Bedrooms = 4,
                            Garden = true,
                            Postcode = "TA2 2AT",
                            Price = 500000m,
                            SellerId = 4,
                            Status = "FORSALE",
                            Type = "HOUSE"
                        });
                });

            modelBuilder.Entity("SetUpEstateAgentDBWeb.Models.Seller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SELLER_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ADDRESS");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("FIRST_NAME");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("PHONE");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("POSTCODE");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("SURNAME");

                    b.HasKey("Id");

                    b.ToTable("seller");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "3 the Long Street",
                            FirstName = "Dilpreet",
                            Phone = "08700333333",
                            Postcode = "AV3 3VA",
                            Surname = "Baradaran"
                        },
                        new
                        {
                            Id = 2,
                            Address = "2 the Short Street",
                            FirstName = "Kofi",
                            Phone = "087004444444",
                            Postcode = "AV4 4VA",
                            Surname = "Dhillon"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
